# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20160415_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='sms',
            field=models.TextField(blank=True),
        ),
    ]
