# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_channel_sms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='sms',
        ),
    ]
